### PR TITLE
Update bower dependencies

### PR DESCRIPTION
**Pull request by zliebersbach**

### CODE REVIEW

**Comment by zliebersbach** [comment]
@LM450N Fixed issue #20 and all API changes. Also improved toast positioning.

**Comment by zliebersbach** [comment]
Seems like the CI is broken, too. Just FYI. :+1:

**Comment by masonlouchart** [comment]
Thank you for your help. There is a little change. The toasters positioned at the top should come from top to bottom, like they do in the last version.

**Comment by masonlouchart** [comment]
LGTM

**Comment by zliebersbach** [comment]
@LM450N Working on the issue you described ATM.

**Comment by masonlouchart** [comment]
@wincinderith I fixed it 😉

**Comment by zliebersbach** [comment]
@LM450N Cool. :+1:

**Comment by zliebersbach** [comment]
@LM450N Issue #20 can be closed.

**Comment by masonlouchart** [comment]
@wincinderith Yep, I forgot to do it in the commit message 😞

**Pull request merged**
